baseURL: http://vnsnippets.github.io/
languageCode: en-us
title: Vidush H. Namah | Blog
theme: hugo-stack

paginate: 5

languages:
    en:
        languageName: English
        title: Vidush H. Namah | Blog
        description:
        weight: 1

# disqusShortname = [insert disqus shortname]
googleAnalytics: G-TQV8DS0Z53
# DefaultContentLanguage: en
# hasCJKLanguage: false

permalinks:
    post: /a/:slug/
    page: /:slug/

params:
    mainSections:
        - articles
    featuredImageField: image
    rssFullContent: true
    favicon: img/favicon.png

    footer:
        since:
        customText: ✏️ The best techniques are passed on by the survivors

    dateFormat:
        published: Jan 02, 2006
        lastUpdated: Jan 02, 2006 15:04 UTC

    sidebar:
        compact: false
        emoji: 👨‍💻
        subtitle: It is now 02:11, and I should probably go to sleep 😴
        avatar:
            enabled: true
            local: true
            src: img/headshot.png

    article:
        math: false
        toc: false
        readingTime: true
        license:
            enabled: false
            default: Licensed under MIT

    comments:
        enabled: false
        # provider: disqus

        # disqusjs:
        #     shortname:
        #     apiUrl:
        #     apiKey:
        #     admin:
        #     adminLabel:

        # utterances:
        #     repo:
        #     issueTerm: pathname
        #     label:

        # remark42:
        #     host:
        #     site:
        #     locale:

        # vssue:
        #     platform:
        #     owner:
        #     repo:
        #     clientId:
        #     clientSecret:
        #     autoCreateIssue: false

        # Waline client configuration see: https://waline.js.org/en/reference/client.html
        # waline:
        #     serverURL:
        #     lang:
        #     visitor:
        #     avatar:
        #     emoji:
        #         - https://cdn.jsdelivr.net/gh/walinejs/emojis/weibo
        #     requiredMeta:
        #         - name
        #         - email
        #         - url
        #     placeholder:
        #     locale:
        #         admin: Admin

        # twikoo:
        #     envId:
        #     region:
        #     path:
        #     lang:

        # giscus:
        #     repo:
        #     repoID:
        #     category:
        #     categoryID:
        #     mapping:
        #     strict:
        #     lightTheme:
        #     darkTheme:
        #     reactionsEnabled: 1
        #     emitMetadata: 0
        #     inputPosition:
        #     lang:

        # gitalk:
        #     owner:
        #     admin:
        #     repo:
        #     clientID:
        #     clientSecret:

        # cusdis:
        #     host:
        #     id:

    widgets:
        homepage:
            - type: search
            - type: archives
              params:
                  limit: 5
            - type: categories
              params:
                  limit: 10
            - type: tag-cloud
              params:
                  limit: 10

    opengraph:
        twitter:
            # Your Twitter username
            site: VHNamah

            # Available values: summary, summary_large_image
            card: summary_large_image

    defaultImage:
        opengraph:
            enabled: false
            local: false
            src:

    colorScheme:
        # Display toggle
        toggle: true

        # Available values: auto, light, dark
        default: auto

    imageProcessing:
        cover:
            enabled: true
        content:
            enabled: true

    errors:
        contentListEmpty:
            - Writing the first blog article is always a challenge 🪶
            - Stay connected.

### Custom menu
### To remove about, archive and search page menu item, remove `menu` field from their FrontMatter
menu:
    main: []

    social:
        - identifier: github
          name: GitHub
          url: https://github.com/vnsnippets
          params:
              icon: brand-github

        # - identifier: twitter
        #   name: Twitter
        #   url: https://twitter.com/vhnamah
        #   params:
        #       icon: brand-twitter

        - identifier: linkedin
          name: LinkedIn
          url: https://linkedin.com/in/vnamah
          params:
              icon: brand-linkedin

        - identifier: instagram
          name: Instagram
          url: https://instagram.com/vnsnippets
          params:
              icon: brand-instagram

related:
    includeNewer: true
    threshold: 60
    toLower: false
    indices:
        - name: tags
          weight: 100

        - name: categories
          weight: 200

markup:
    goldmark:
        renderer:
            ## Set to true if you have HTML content inside Markdown
            unsafe: false
    # tableOfContents:
    #     endLevel: 4
    #     ordered: true
    #     startLevel: 3
    highlight:
        noClasses: false
        codeFences: true
        guessSyntax: true
        lineNoStart: 1
        lineNos: true
        lineNumbersInTable: true
        tabWidth: 4
