BaseURL: 'https://vnsnippets.github.io/'
LanguageCode: "en"

Theme: lithium

# Site Title
Title: Vidush H. Namah

Paginate: 12

googleAnalytics: G-TQV8DS0Z53

PERMALINKS:
  Page: /:slug/
  Post: /a/:slugorfilename/

PARAMS:
  Image: meta.jpg
  Avatar: avatar.png
  Author: "Vidush H. Namah"

  Directory: "articles"
  
  Articles:
    Dateformat: "2006.01.02"

  Theme:
    Toggle: true
    Default: light
    Coloured:
      Social: false
      Preview: true
  
  Footer:
    Since: 2014
    Report:
      Bugs: https://github.com/vnsnippets/vnsnippets.github.io/issues/new

RELATED:
  IncludeNewer: true
  Threshold: 60
  ToLower: false
  Indices:
    - Name: series
      Weight: 100

Markup:
  # Code previews settings
  Highlight:
    NoClasses: true
    CodeFences: true
    GuessSyntax: true
    TabWidth: 4
    LineNoStart: 1
    LineNos: true

Youtube:
  PrivacyEnhanced: true

TAXONOMIES:
  Series: series

LANGUAGES:
  EN:
    MENU:
      Main:
      - Name: Home
        URL: /
        Weight: 10

      - Name: Gallery
        URL: /gallery
        Weight: 20

      - Name: About
        URL: /about
        Weight: 30
      
      Social:
      - Name: GitHub
        URL: https://github.com/vnsnippets

      - Name: LinkedIn
        URL: https://linkedin.com/in/vnamah

      - Name: Instagram
        URL: https://instagram.com/the.frame.drops
        
    PARAMS:
      Description: "With a blend of creativity and precision, I craft digital solutions that bridge the gap between imagination and reality. Away from my screens, photography is my escape — a way to freeze time, evoke emotions, and tell stories."
      Keywords: [ "Technology", "Photography" ]
      Translations:
        FooterMessage: Vidush H. Namah
        DefaultArticlesMessage: NO CONTENT AVAILABLE
        RelatedContentHeader: "Related Articles"
        ThemeLabel:
          Light: LIGHT MODE (BETA)
          Dark: DARK MODE